name: "generate-ensembles"
on:
  workflow_dispatch:
  schedule:
  - cron: "30 11,12,13,14 * * *"
  
jobs:
  generate-ensembles:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
        
    - name: Setup R
      uses: r-lib/actions/setup-r@v2 
      with:
        r-version: '4.2.3'
      
    - name: Generate ensembles
      run: |
        Rscript ./code/ensemble/generate_ensembles.R
    
#     - name: Commit files
#       env:
#         AUTH: ${{ secrets.GITHUBTOKEN }}
#       run: |
#         git config --local user.email "action@github.com"
#         git config --local user.name "GitHub Action - Generate Ensembles"
#         git remote rm origin
#         git remote add origin https://${AUTH}@github.com/KITmetricslab/hospitalization-nowcast-hub.git > /dev/null 2>&1
#         git pull origin main
#         git add --all
#         git commit --allow-empty -m "Daily ensemble update"
        
#     - name: Push changes
#       run: |
#         git push --quiet --set-upstream origin HEAD:main
#         echo "pushed to github"

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUBTOKEN }}
        commit-message: Update ensembles
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: update-ensembles
        delete-branch: true
        title: 'Update ensembles'
        body: |
          Update ensembles
        labels: |
          automated pr
        reviewers: jbracher
